# Profile: dev
spring.thymeleaf.prefix=file:src/main/resources/templates/
spring.web.resources.static-locations=file:src/main/resources/static/,classpath:/static/
logging.level.org.springframework.web=DEBUG
